spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    url: ${LOCAL_DB_URL}
  output:
    ansi:
      enabled: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: false
        use_sql_comments: false
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  logging:
    level:
      org:
        hibernate:
          type: trace
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${kakao.client.id}
            client-secret: ${kakao.client.secret}
            client-authentication-method: POST
            scope:
              - profile_nickname
              - account_email
              - profile_image
            redirect-uri: http://api.drop-the-beatbox.store/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  header: Authorization
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
  authorities-key: authoritiesKey
  access-token-validity-in-seconds: 1210000000 # 30 m
  refresh-token-validity-in-seconds: 1210000000 # 14 d
#  1800000
springdoc:
  use-fqn: true

cloud:
  aws:
    s3:
      bucket: field-mate
      folder: dtbb
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${aws.access.key.id}
      secretKey: ${aws.secret.access.key}
    cloudFront:
      distributionDomain: https://d3j1uqx77q4q2.cloudfront.net
